---
- name: Start 10 nginx contianers on all maanged nodes
  hosts: all
  tasks:
   - name: Create 10 nginx
     docker_container:
      image: nginx
      name: "container{{item}}"
     with_sequence: count=10
