---
- name: Create users on managed node
  hosts: webserver
  tasks:
   - name: Create a user
     user:
      name: Anu
      password: intelliqit
      uid: 1357
      home: /home/Anu
      shell: /bin/bash

...
