---
- name: Install/uninstal
  hosts: all
  vars:
   - a: tomcat8
   - b: present
   - c: no
  tasks:
   - name: Install uninstall s/w packages
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
...

