---
- name: Working on docker containers
  hosts: all
  tasks:
   - name: Start a httpd container
     docker_container:
      image: httpd
      name: h1
   - name: Stop the httpd container
     docker_container:
      name: h1
      state: stopped
   - name: Delete the httpd container
     docker_container:
      name: h1
      state: absent
